// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/sentinelruntime/v1/runtime.proto

package sentinelruntimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalStatus int32

const (
	SignalStatus_SIGNAL_STATUS_UNSPECIFIED SignalStatus = 0
	SignalStatus_SIGNAL_STATUS_HEALTHY     SignalStatus = 1
	SignalStatus_SIGNAL_STATUS_UNHEALTHY   SignalStatus = 2
	SignalStatus_SIGNAL_STATUS_UNKNOWN     SignalStatus = 3
)

// Enum value maps for SignalStatus.
var (
	SignalStatus_name = map[int32]string{
		0: "SIGNAL_STATUS_UNSPECIFIED",
		1: "SIGNAL_STATUS_HEALTHY",
		2: "SIGNAL_STATUS_UNHEALTHY",
		3: "SIGNAL_STATUS_UNKNOWN",
	}
	SignalStatus_value = map[string]int32{
		"SIGNAL_STATUS_UNSPECIFIED": 0,
		"SIGNAL_STATUS_HEALTHY":     1,
		"SIGNAL_STATUS_UNHEALTHY":   2,
		"SIGNAL_STATUS_UNKNOWN":     3,
	}
)

func (x SignalStatus) Enum() *SignalStatus {
	p := new(SignalStatus)
	*p = x
	return p
}

func (x SignalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sentinelruntime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (SignalStatus) Type() protoreflect.EnumType {
	return &file_proto_sentinelruntime_v1_runtime_proto_enumTypes[0]
}

func (x SignalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalStatus.Descriptor instead.
func (SignalStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_sentinelruntime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type RuntimeErrorCode int32

const (
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSPECIFIED      RuntimeErrorCode = 0
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSUPPORTED_TYPE RuntimeErrorCode = 1
	RuntimeErrorCode_RUNTIME_ERROR_CODE_INVALID_CONFIG   RuntimeErrorCode = 2
	RuntimeErrorCode_RUNTIME_ERROR_CODE_CHECK_FAILED     RuntimeErrorCode = 3
	RuntimeErrorCode_RUNTIME_ERROR_CODE_INTERNAL         RuntimeErrorCode = 4
)

// Enum value maps for RuntimeErrorCode.
var (
	RuntimeErrorCode_name = map[int32]string{
		0: "RUNTIME_ERROR_CODE_UNSPECIFIED",
		1: "RUNTIME_ERROR_CODE_UNSUPPORTED_TYPE",
		2: "RUNTIME_ERROR_CODE_INVALID_CONFIG",
		3: "RUNTIME_ERROR_CODE_CHECK_FAILED",
		4: "RUNTIME_ERROR_CODE_INTERNAL",
	}
	RuntimeErrorCode_value = map[string]int32{
		"RUNTIME_ERROR_CODE_UNSPECIFIED":      0,
		"RUNTIME_ERROR_CODE_UNSUPPORTED_TYPE": 1,
		"RUNTIME_ERROR_CODE_INVALID_CONFIG":   2,
		"RUNTIME_ERROR_CODE_CHECK_FAILED":     3,
		"RUNTIME_ERROR_CODE_INTERNAL":         4,
	}
)

func (x RuntimeErrorCode) Enum() *RuntimeErrorCode {
	p := new(RuntimeErrorCode)
	*p = x
	return p
}

func (x RuntimeErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sentinelruntime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (RuntimeErrorCode) Type() protoreflect.EnumType {
	return &file_proto_sentinelruntime_v1_runtime_proto_enumTypes[1]
}

func (x RuntimeErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeErrorCode.Descriptor instead.
func (RuntimeErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_sentinelruntime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

type CheckRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AlarmId      string                 `protobuf:"bytes,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	SentinelType string                 `protobuf:"bytes,2,opt,name=sentinel_type,json=sentinelType,proto3" json:"sentinel_type,omitempty"`
	// config_json is intentionally opaque to Mirante core.
	// The worker forwards raw JSON bytes and each runner implementation
	// parses/validates config in its own runtime.
	// This keeps sentinel implementations language-agnostic and allows
	// private/external runners in any language/repository.
	ConfigJson    []byte `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_proto_sentinelruntime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinelruntime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentinelruntime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

func (x *CheckRequest) GetSentinelType() string {
	if x != nil {
		return x.SentinelType
	}
	return ""
}

func (x *CheckRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          RuntimeErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=sentinelruntime.v1.RuntimeErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_proto_sentinelruntime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinelruntime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_proto_sentinelruntime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeError) GetCode() RuntimeErrorCode {
	if x != nil {
		return x.Code
	}
	return RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSPECIFIED
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  SignalStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=sentinelruntime.v1.SignalStatus" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// error is optional and set when sentinel execution could not be completed
	// as expected (for example, invalid config or unsupported type).
	Error         *RuntimeError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_proto_sentinelruntime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinelruntime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentinelruntime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResponse) GetStatus() SignalStatus {
	if x != nil {
		return x.Status
	}
	return SignalStatus_SIGNAL_STATUS_UNSPECIFIED
}

func (x *CheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckResponse) GetError() *RuntimeError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_sentinelruntime_v1_runtime_proto protoreflect.FileDescriptor

const file_proto_sentinelruntime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"&proto/sentinelruntime/v1/runtime.proto\x12\x12sentinelruntime.v1\"o\n" +
	"\fCheckRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\tR\aalarmId\x12#\n" +
	"\rsentinel_type\x18\x02 \x01(\tR\fsentinelType\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\"b\n" +
	"\fRuntimeError\x128\n" +
	"\x04code\x18\x01 \x01(\x0e2$.sentinelruntime.v1.RuntimeErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\rCheckResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .sentinelruntime.v1.SignalStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x05error\x18\x03 \x01(\v2 .sentinelruntime.v1.RuntimeErrorR\x05error*\x80\x01\n" +
	"\fSignalStatus\x12\x1d\n" +
	"\x19SIGNAL_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SIGNAL_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17SIGNAL_STATUS_UNHEALTHY\x10\x02\x12\x19\n" +
	"\x15SIGNAL_STATUS_UNKNOWN\x10\x03*\xcc\x01\n" +
	"\x10RuntimeErrorCode\x12\"\n" +
	"\x1eRUNTIME_ERROR_CODE_UNSPECIFIED\x10\x00\x12'\n" +
	"#RUNTIME_ERROR_CODE_UNSUPPORTED_TYPE\x10\x01\x12%\n" +
	"!RUNTIME_ERROR_CODE_INVALID_CONFIG\x10\x02\x12#\n" +
	"\x1fRUNTIME_ERROR_CODE_CHECK_FAILED\x10\x03\x12\x1f\n" +
	"\x1bRUNTIME_ERROR_CODE_INTERNAL\x10\x042_\n" +
	"\x0fSentinelRuntime\x12L\n" +
	"\x05Check\x12 .sentinelruntime.v1.CheckRequest\x1a!.sentinelruntime.v1.CheckResponseBJZHgithub.com/g0ulartleo/mirante/proto/sentinelruntime/v1;sentinelruntimev1b\x06proto3"

var (
	file_proto_sentinelruntime_v1_runtime_proto_rawDescOnce sync.Once
	file_proto_sentinelruntime_v1_runtime_proto_rawDescData []byte
)

func file_proto_sentinelruntime_v1_runtime_proto_rawDescGZIP() []byte {
	file_proto_sentinelruntime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_proto_sentinelruntime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentinelruntime_v1_runtime_proto_rawDesc), len(file_proto_sentinelruntime_v1_runtime_proto_rawDesc)))
	})
	return file_proto_sentinelruntime_v1_runtime_proto_rawDescData
}

var file_proto_sentinelruntime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_sentinelruntime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sentinelruntime_v1_runtime_proto_goTypes = []any{
	(SignalStatus)(0),     // 0: sentinelruntime.v1.SignalStatus
	(RuntimeErrorCode)(0), // 1: sentinelruntime.v1.RuntimeErrorCode
	(*CheckRequest)(nil),  // 2: sentinelruntime.v1.CheckRequest
	(*RuntimeError)(nil),  // 3: sentinelruntime.v1.RuntimeError
	(*CheckResponse)(nil), // 4: sentinelruntime.v1.CheckResponse
}
var file_proto_sentinelruntime_v1_runtime_proto_depIdxs = []int32{
	1, // 0: sentinelruntime.v1.RuntimeError.code:type_name -> sentinelruntime.v1.RuntimeErrorCode
	0, // 1: sentinelruntime.v1.CheckResponse.status:type_name -> sentinelruntime.v1.SignalStatus
	3, // 2: sentinelruntime.v1.CheckResponse.error:type_name -> sentinelruntime.v1.RuntimeError
	2, // 3: sentinelruntime.v1.SentinelRuntime.Check:input_type -> sentinelruntime.v1.CheckRequest
	4, // 4: sentinelruntime.v1.SentinelRuntime.Check:output_type -> sentinelruntime.v1.CheckResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_sentinelruntime_v1_runtime_proto_init() }
func file_proto_sentinelruntime_v1_runtime_proto_init() {
	if File_proto_sentinelruntime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentinelruntime_v1_runtime_proto_rawDesc), len(file_proto_sentinelruntime_v1_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentinelruntime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_proto_sentinelruntime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_proto_sentinelruntime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_proto_sentinelruntime_v1_runtime_proto_msgTypes,
	}.Build()
	File_proto_sentinelruntime_v1_runtime_proto = out.File
	file_proto_sentinelruntime_v1_runtime_proto_goTypes = nil
	file_proto_sentinelruntime_v1_runtime_proto_depIdxs = nil
}
