// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/sentinelruntime/v1/runtime.proto

package sentinelruntimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentinelRuntime_Check_FullMethodName = "/sentinelruntime.v1.SentinelRuntime/Check"
)

// SentinelRuntimeClient is the client API for SentinelRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelRuntimeClient interface {
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type sentinelRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelRuntimeClient(cc grpc.ClientConnInterface) SentinelRuntimeClient {
	return &sentinelRuntimeClient{cc}
}

func (c *sentinelRuntimeClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, SentinelRuntime_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentinelRuntimeServer is the server API for SentinelRuntime service.
// All implementations must embed UnimplementedSentinelRuntimeServer
// for forward compatibility.
type SentinelRuntimeServer interface {
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedSentinelRuntimeServer()
}

// UnimplementedSentinelRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentinelRuntimeServer struct{}

func (UnimplementedSentinelRuntimeServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSentinelRuntimeServer) mustEmbedUnimplementedSentinelRuntimeServer() {}
func (UnimplementedSentinelRuntimeServer) testEmbeddedByValue()                         {}

// UnsafeSentinelRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelRuntimeServer will
// result in compilation errors.
type UnsafeSentinelRuntimeServer interface {
	mustEmbedUnimplementedSentinelRuntimeServer()
}

func RegisterSentinelRuntimeServer(s grpc.ServiceRegistrar, srv SentinelRuntimeServer) {
	// If the following call pancis, it indicates UnimplementedSentinelRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentinelRuntime_ServiceDesc, srv)
}

func _SentinelRuntime_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelRuntimeServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelRuntime_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelRuntimeServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentinelRuntime_ServiceDesc is the grpc.ServiceDesc for SentinelRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentinelRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinelruntime.v1.SentinelRuntime",
	HandlerType: (*SentinelRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _SentinelRuntime_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sentinelruntime/v1/runtime.proto",
}
