storage:
  driver: redis

redis:
  addr: redis:6379

http:
  addr: 0.0.0.0
  port: "40169"

alarm_runtime:
  timeout: 30s
  runtimes:
    example:
      addr: host.docker.internal:50051

auth:
  api_key: ${API_KEY}
  basic:
    username: ${DASHBOARD_BASIC_AUTH_USERNAME}
    password: ${DASHBOARD_BASIC_AUTH_PASSWORD}
  oauth:
    # enable OAuth authentication
    enabled: false
    provider: google
    redirect_url: http://localhost:40169/auth/callback
    # allowed_domains and allowed_emails are used to restrict access
    # at least one must be set when enabled=true
    allowed_domains: []
    allowed_emails: []
    session_timeout: 24h

smtp:
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
  user: ${SMTP_USER}
  password: ${SMTP_PASSWORD}
