// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/alarmruntime/v1/runtime.proto

package alarmruntimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalStatus int32

const (
	SignalStatus_SIGNAL_STATUS_UNSPECIFIED SignalStatus = 0
	SignalStatus_SIGNAL_STATUS_HEALTHY     SignalStatus = 1
	SignalStatus_SIGNAL_STATUS_UNHEALTHY   SignalStatus = 2
	SignalStatus_SIGNAL_STATUS_UNKNOWN     SignalStatus = 3
	SignalStatus_SIGNAL_STATUS_WARNING     SignalStatus = 4
)

// Enum value maps for SignalStatus.
var (
	SignalStatus_name = map[int32]string{
		0: "SIGNAL_STATUS_UNSPECIFIED",
		1: "SIGNAL_STATUS_HEALTHY",
		2: "SIGNAL_STATUS_UNHEALTHY",
		3: "SIGNAL_STATUS_UNKNOWN",
		4: "SIGNAL_STATUS_WARNING",
	}
	SignalStatus_value = map[string]int32{
		"SIGNAL_STATUS_UNSPECIFIED": 0,
		"SIGNAL_STATUS_HEALTHY":     1,
		"SIGNAL_STATUS_UNHEALTHY":   2,
		"SIGNAL_STATUS_UNKNOWN":     3,
		"SIGNAL_STATUS_WARNING":     4,
	}
)

func (x SignalStatus) Enum() *SignalStatus {
	p := new(SignalStatus)
	*p = x
	return p
}

func (x SignalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_alarmruntime_v1_runtime_proto_enumTypes[0].Descriptor()
}

func (SignalStatus) Type() protoreflect.EnumType {
	return &file_proto_alarmruntime_v1_runtime_proto_enumTypes[0]
}

func (x SignalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalStatus.Descriptor instead.
func (SignalStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type RuntimeErrorCode int32

const (
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSPECIFIED     RuntimeErrorCode = 0
	RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSUPPORTED     RuntimeErrorCode = 1
	RuntimeErrorCode_RUNTIME_ERROR_CODE_RUNALARM_FAILED RuntimeErrorCode = 2
	RuntimeErrorCode_RUNTIME_ERROR_CODE_INTERNAL        RuntimeErrorCode = 3
)

// Enum value maps for RuntimeErrorCode.
var (
	RuntimeErrorCode_name = map[int32]string{
		0: "RUNTIME_ERROR_CODE_UNSPECIFIED",
		1: "RUNTIME_ERROR_CODE_UNSUPPORTED",
		2: "RUNTIME_ERROR_CODE_RUNALARM_FAILED",
		3: "RUNTIME_ERROR_CODE_INTERNAL",
	}
	RuntimeErrorCode_value = map[string]int32{
		"RUNTIME_ERROR_CODE_UNSPECIFIED":     0,
		"RUNTIME_ERROR_CODE_UNSUPPORTED":     1,
		"RUNTIME_ERROR_CODE_RUNALARM_FAILED": 2,
		"RUNTIME_ERROR_CODE_INTERNAL":        3,
	}
)

func (x RuntimeErrorCode) Enum() *RuntimeErrorCode {
	p := new(RuntimeErrorCode)
	*p = x
	return p
}

func (x RuntimeErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_alarmruntime_v1_runtime_proto_enumTypes[1].Descriptor()
}

func (RuntimeErrorCode) Type() protoreflect.EnumType {
	return &file_proto_alarmruntime_v1_runtime_proto_enumTypes[1]
}

func (x RuntimeErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeErrorCode.Descriptor instead.
func (RuntimeErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListAlarmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlarmsRequest) Reset() {
	*x = ListAlarmsRequest{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlarmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlarmsRequest) ProtoMessage() {}

func (x *ListAlarmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlarmsRequest.ProtoReflect.Descriptor instead.
func (*ListAlarmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

type ListAlarmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alarms        []*Alarm               `protobuf:"bytes,1,rep,name=alarms,proto3" json:"alarms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlarmsResponse) Reset() {
	*x = ListAlarmsResponse{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlarmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlarmsResponse) ProtoMessage() {}

func (x *ListAlarmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlarmsResponse.ProtoReflect.Descriptor instead.
func (*ListAlarmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlarmsResponse) GetAlarms() []*Alarm {
	if x != nil {
		return x.Alarms
	}
	return nil
}

type GetAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlarmId       string                 `protobuf:"bytes,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlarmRequest) Reset() {
	*x = GetAlarmRequest{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlarmRequest) ProtoMessage() {}

func (x *GetAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlarmRequest.ProtoReflect.Descriptor instead.
func (*GetAlarmRequest) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlarmRequest) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

type GetAlarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alarm         *Alarm                 `protobuf:"bytes,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlarmResponse) Reset() {
	*x = GetAlarmResponse{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlarmResponse) ProtoMessage() {}

func (x *GetAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlarmResponse.ProtoReflect.Descriptor instead.
func (*GetAlarmResponse) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *GetAlarmResponse) GetAlarm() *Alarm {
	if x != nil {
		return x.Alarm
	}
	return nil
}

type RunAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlarmId       string                 `protobuf:"bytes,1,opt,name=alarm_id,json=alarmId,proto3" json:"alarm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAlarmRequest) Reset() {
	*x = RunAlarmRequest{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAlarmRequest) ProtoMessage() {}

func (x *RunAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAlarmRequest.ProtoReflect.Descriptor instead.
func (*RunAlarmRequest) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *RunAlarmRequest) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

type RunAlarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SignalStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=alarmruntime.v1.SignalStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *RuntimeError          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Details       []*structpb.Struct     `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAlarmResponse) Reset() {
	*x = RunAlarmResponse{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAlarmResponse) ProtoMessage() {}

func (x *RunAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAlarmResponse.ProtoReflect.Descriptor instead.
func (*RunAlarmResponse) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *RunAlarmResponse) GetStatus() SignalStatus {
	if x != nil {
		return x.Status
	}
	return SignalStatus_SIGNAL_STATUS_UNSPECIFIED
}

func (x *RunAlarmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunAlarmResponse) GetError() *RuntimeError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RunAlarmResponse) GetDetails() []*structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          RuntimeErrorCode       `protobuf:"varint,1,opt,name=code,proto3,enum=alarmruntime.v1.RuntimeErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeError) GetCode() RuntimeErrorCode {
	if x != nil {
		return x.Code
	}
	return RuntimeErrorCode_RUNTIME_ERROR_CODE_UNSPECIFIED
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Alarm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	HowToFix      string                 `protobuf:"bytes,4,opt,name=how_to_fix,json=howToFix,proto3" json:"how_to_fix,omitempty"`
	Path          []string               `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	Cron          string                 `protobuf:"bytes,6,opt,name=cron,proto3" json:"cron,omitempty"`
	Interval      string                 `protobuf:"bytes,7,opt,name=interval,proto3" json:"interval,omitempty"`
	Notifications *AlarmNotifications    `protobuf:"bytes,8,opt,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *Alarm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alarm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alarm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alarm) GetHowToFix() string {
	if x != nil {
		return x.HowToFix
	}
	return ""
}

func (x *Alarm) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Alarm) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *Alarm) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *Alarm) GetNotifications() *AlarmNotifications {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type AlarmNotifications struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	SlackWebhooks        []*SlackWebhookNotification `protobuf:"bytes,1,rep,name=slack_webhooks,json=slackWebhooks,proto3" json:"slack_webhooks,omitempty"`
	Emails               []*EmailNotification        `protobuf:"bytes,2,rep,name=emails,proto3" json:"emails,omitempty"`
	NotifyMissingSignals bool                        `protobuf:"varint,3,opt,name=notify_missing_signals,json=notifyMissingSignals,proto3" json:"notify_missing_signals,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AlarmNotifications) Reset() {
	*x = AlarmNotifications{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmNotifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmNotifications) ProtoMessage() {}

func (x *AlarmNotifications) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmNotifications.ProtoReflect.Descriptor instead.
func (*AlarmNotifications) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *AlarmNotifications) GetSlackWebhooks() []*SlackWebhookNotification {
	if x != nil {
		return x.SlackWebhooks
	}
	return nil
}

func (x *AlarmNotifications) GetEmails() []*EmailNotification {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *AlarmNotifications) GetNotifyMissingSignals() bool {
	if x != nil {
		return x.NotifyMissingSignals
	}
	return false
}

type SlackWebhookNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlackWebhookNotification) Reset() {
	*x = SlackWebhookNotification{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlackWebhookNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackWebhookNotification) ProtoMessage() {}

func (x *SlackWebhookNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackWebhookNotification.ProtoReflect.Descriptor instead.
func (*SlackWebhookNotification) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *SlackWebhookNotification) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type EmailNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailNotification) Reset() {
	*x = EmailNotification{}
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailNotification) ProtoMessage() {}

func (x *EmailNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alarmruntime_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailNotification.ProtoReflect.Descriptor instead.
func (*EmailNotification) Descriptor() ([]byte, []int) {
	return file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *EmailNotification) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

var File_proto_alarmruntime_v1_runtime_proto protoreflect.FileDescriptor

const file_proto_alarmruntime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"#proto/alarmruntime/v1/runtime.proto\x12\x0falarmruntime.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x13\n" +
	"\x11ListAlarmsRequest\"D\n" +
	"\x12ListAlarmsResponse\x12.\n" +
	"\x06alarms\x18\x01 \x03(\v2\x16.alarmruntime.v1.AlarmR\x06alarms\",\n" +
	"\x0fGetAlarmRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\tR\aalarmId\"@\n" +
	"\x10GetAlarmResponse\x12,\n" +
	"\x05alarm\x18\x01 \x01(\v2\x16.alarmruntime.v1.AlarmR\x05alarm\",\n" +
	"\x0fRunAlarmRequest\x12\x19\n" +
	"\balarm_id\x18\x01 \x01(\tR\aalarmId\"\xcb\x01\n" +
	"\x10RunAlarmResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.alarmruntime.v1.SignalStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x05error\x18\x03 \x01(\v2\x1d.alarmruntime.v1.RuntimeErrorR\x05error\x121\n" +
	"\adetails\x18\x04 \x03(\v2\x17.google.protobuf.StructR\adetails\"_\n" +
	"\fRuntimeError\x125\n" +
	"\x04code\x18\x01 \x01(\x0e2!.alarmruntime.v1.RuntimeErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfa\x01\n" +
	"\x05Alarm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\n" +
	"how_to_fix\x18\x04 \x01(\tR\bhowToFix\x12\x12\n" +
	"\x04path\x18\x05 \x03(\tR\x04path\x12\x12\n" +
	"\x04cron\x18\x06 \x01(\tR\x04cron\x12\x1a\n" +
	"\binterval\x18\a \x01(\tR\binterval\x12I\n" +
	"\rnotifications\x18\b \x01(\v2#.alarmruntime.v1.AlarmNotificationsR\rnotifications\"\xd8\x01\n" +
	"\x12AlarmNotifications\x12P\n" +
	"\x0eslack_webhooks\x18\x01 \x03(\v2).alarmruntime.v1.SlackWebhookNotificationR\rslackWebhooks\x12:\n" +
	"\x06emails\x18\x02 \x03(\v2\".alarmruntime.v1.EmailNotificationR\x06emails\x124\n" +
	"\x16notify_missing_signals\x18\x03 \x01(\bR\x14notifyMissingSignals\",\n" +
	"\x18SlackWebhookNotification\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"#\n" +
	"\x11EmailNotification\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to*\x9b\x01\n" +
	"\fSignalStatus\x12\x1d\n" +
	"\x19SIGNAL_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SIGNAL_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17SIGNAL_STATUS_UNHEALTHY\x10\x02\x12\x19\n" +
	"\x15SIGNAL_STATUS_UNKNOWN\x10\x03\x12\x19\n" +
	"\x15SIGNAL_STATUS_WARNING\x10\x04*\xa3\x01\n" +
	"\x10RuntimeErrorCode\x12\"\n" +
	"\x1eRUNTIME_ERROR_CODE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eRUNTIME_ERROR_CODE_UNSUPPORTED\x10\x01\x12&\n" +
	"\"RUNTIME_ERROR_CODE_RUNALARM_FAILED\x10\x02\x12\x1f\n" +
	"\x1bRUNTIME_ERROR_CODE_INTERNAL\x10\x032\xd2\x02\n" +
	"\fAlarmRuntime\x12U\n" +
	"\n" +
	"ListAlarms\x12\".alarmruntime.v1.ListAlarmsRequest\x1a#.alarmruntime.v1.ListAlarmsResponse\x12O\n" +
	"\bGetAlarm\x12 .alarmruntime.v1.GetAlarmRequest\x1a!.alarmruntime.v1.GetAlarmResponse\x12O\n" +
	"\bRunAlarm\x12 .alarmruntime.v1.RunAlarmRequest\x1a!.alarmruntime.v1.RunAlarmResponse\x12I\n" +
	"\x06Health\x12\x1e.alarmruntime.v1.HealthRequest\x1a\x1f.alarmruntime.v1.HealthResponseBDZBgithub.com/g0ulartleo/mirante/proto/alarmruntime/v1;alarmruntimev1b\x06proto3"

var (
	file_proto_alarmruntime_v1_runtime_proto_rawDescOnce sync.Once
	file_proto_alarmruntime_v1_runtime_proto_rawDescData []byte
)

func file_proto_alarmruntime_v1_runtime_proto_rawDescGZIP() []byte {
	file_proto_alarmruntime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_proto_alarmruntime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alarmruntime_v1_runtime_proto_rawDesc), len(file_proto_alarmruntime_v1_runtime_proto_rawDesc)))
	})
	return file_proto_alarmruntime_v1_runtime_proto_rawDescData
}

var file_proto_alarmruntime_v1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_alarmruntime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_alarmruntime_v1_runtime_proto_goTypes = []any{
	(SignalStatus)(0),                // 0: alarmruntime.v1.SignalStatus
	(RuntimeErrorCode)(0),            // 1: alarmruntime.v1.RuntimeErrorCode
	(*HealthRequest)(nil),            // 2: alarmruntime.v1.HealthRequest
	(*HealthResponse)(nil),           // 3: alarmruntime.v1.HealthResponse
	(*ListAlarmsRequest)(nil),        // 4: alarmruntime.v1.ListAlarmsRequest
	(*ListAlarmsResponse)(nil),       // 5: alarmruntime.v1.ListAlarmsResponse
	(*GetAlarmRequest)(nil),          // 6: alarmruntime.v1.GetAlarmRequest
	(*GetAlarmResponse)(nil),         // 7: alarmruntime.v1.GetAlarmResponse
	(*RunAlarmRequest)(nil),          // 8: alarmruntime.v1.RunAlarmRequest
	(*RunAlarmResponse)(nil),         // 9: alarmruntime.v1.RunAlarmResponse
	(*RuntimeError)(nil),             // 10: alarmruntime.v1.RuntimeError
	(*Alarm)(nil),                    // 11: alarmruntime.v1.Alarm
	(*AlarmNotifications)(nil),       // 12: alarmruntime.v1.AlarmNotifications
	(*SlackWebhookNotification)(nil), // 13: alarmruntime.v1.SlackWebhookNotification
	(*EmailNotification)(nil),        // 14: alarmruntime.v1.EmailNotification
	(*structpb.Struct)(nil),          // 15: google.protobuf.Struct
}
var file_proto_alarmruntime_v1_runtime_proto_depIdxs = []int32{
	11, // 0: alarmruntime.v1.ListAlarmsResponse.alarms:type_name -> alarmruntime.v1.Alarm
	11, // 1: alarmruntime.v1.GetAlarmResponse.alarm:type_name -> alarmruntime.v1.Alarm
	0,  // 2: alarmruntime.v1.RunAlarmResponse.status:type_name -> alarmruntime.v1.SignalStatus
	10, // 3: alarmruntime.v1.RunAlarmResponse.error:type_name -> alarmruntime.v1.RuntimeError
	15, // 4: alarmruntime.v1.RunAlarmResponse.details:type_name -> google.protobuf.Struct
	1,  // 5: alarmruntime.v1.RuntimeError.code:type_name -> alarmruntime.v1.RuntimeErrorCode
	12, // 6: alarmruntime.v1.Alarm.notifications:type_name -> alarmruntime.v1.AlarmNotifications
	13, // 7: alarmruntime.v1.AlarmNotifications.slack_webhooks:type_name -> alarmruntime.v1.SlackWebhookNotification
	14, // 8: alarmruntime.v1.AlarmNotifications.emails:type_name -> alarmruntime.v1.EmailNotification
	4,  // 9: alarmruntime.v1.AlarmRuntime.ListAlarms:input_type -> alarmruntime.v1.ListAlarmsRequest
	6,  // 10: alarmruntime.v1.AlarmRuntime.GetAlarm:input_type -> alarmruntime.v1.GetAlarmRequest
	8,  // 11: alarmruntime.v1.AlarmRuntime.RunAlarm:input_type -> alarmruntime.v1.RunAlarmRequest
	2,  // 12: alarmruntime.v1.AlarmRuntime.Health:input_type -> alarmruntime.v1.HealthRequest
	5,  // 13: alarmruntime.v1.AlarmRuntime.ListAlarms:output_type -> alarmruntime.v1.ListAlarmsResponse
	7,  // 14: alarmruntime.v1.AlarmRuntime.GetAlarm:output_type -> alarmruntime.v1.GetAlarmResponse
	9,  // 15: alarmruntime.v1.AlarmRuntime.RunAlarm:output_type -> alarmruntime.v1.RunAlarmResponse
	3,  // 16: alarmruntime.v1.AlarmRuntime.Health:output_type -> alarmruntime.v1.HealthResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_alarmruntime_v1_runtime_proto_init() }
func file_proto_alarmruntime_v1_runtime_proto_init() {
	if File_proto_alarmruntime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alarmruntime_v1_runtime_proto_rawDesc), len(file_proto_alarmruntime_v1_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alarmruntime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_proto_alarmruntime_v1_runtime_proto_depIdxs,
		EnumInfos:         file_proto_alarmruntime_v1_runtime_proto_enumTypes,
		MessageInfos:      file_proto_alarmruntime_v1_runtime_proto_msgTypes,
	}.Build()
	File_proto_alarmruntime_v1_runtime_proto = out.File
	file_proto_alarmruntime_v1_runtime_proto_goTypes = nil
	file_proto_alarmruntime_v1_runtime_proto_depIdxs = nil
}
