// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/alarmruntime/v1/runtime.proto

package alarmruntimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlarmRuntime_ListAlarms_FullMethodName = "/alarmruntime.v1.AlarmRuntime/ListAlarms"
	AlarmRuntime_GetAlarm_FullMethodName   = "/alarmruntime.v1.AlarmRuntime/GetAlarm"
	AlarmRuntime_RunAlarm_FullMethodName   = "/alarmruntime.v1.AlarmRuntime/RunAlarm"
)

// AlarmRuntimeClient is the client API for AlarmRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlarmRuntimeClient interface {
	ListAlarms(ctx context.Context, in *ListAlarmsRequest, opts ...grpc.CallOption) (*ListAlarmsResponse, error)
	GetAlarm(ctx context.Context, in *GetAlarmRequest, opts ...grpc.CallOption) (*GetAlarmResponse, error)
	RunAlarm(ctx context.Context, in *RunAlarmRequest, opts ...grpc.CallOption) (*RunAlarmResponse, error)
}

type alarmRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmRuntimeClient(cc grpc.ClientConnInterface) AlarmRuntimeClient {
	return &alarmRuntimeClient{cc}
}

func (c *alarmRuntimeClient) ListAlarms(ctx context.Context, in *ListAlarmsRequest, opts ...grpc.CallOption) (*ListAlarmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlarmsResponse)
	err := c.cc.Invoke(ctx, AlarmRuntime_ListAlarms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmRuntimeClient) GetAlarm(ctx context.Context, in *GetAlarmRequest, opts ...grpc.CallOption) (*GetAlarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlarmResponse)
	err := c.cc.Invoke(ctx, AlarmRuntime_GetAlarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmRuntimeClient) RunAlarm(ctx context.Context, in *RunAlarmRequest, opts ...grpc.CallOption) (*RunAlarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAlarmResponse)
	err := c.cc.Invoke(ctx, AlarmRuntime_RunAlarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmRuntimeServer is the server API for AlarmRuntime service.
// All implementations must embed UnimplementedAlarmRuntimeServer
// for forward compatibility.
type AlarmRuntimeServer interface {
	ListAlarms(context.Context, *ListAlarmsRequest) (*ListAlarmsResponse, error)
	GetAlarm(context.Context, *GetAlarmRequest) (*GetAlarmResponse, error)
	RunAlarm(context.Context, *RunAlarmRequest) (*RunAlarmResponse, error)
	mustEmbedUnimplementedAlarmRuntimeServer()
}

// UnimplementedAlarmRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlarmRuntimeServer struct{}

func (UnimplementedAlarmRuntimeServer) ListAlarms(context.Context, *ListAlarmsRequest) (*ListAlarmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlarms not implemented")
}
func (UnimplementedAlarmRuntimeServer) GetAlarm(context.Context, *GetAlarmRequest) (*GetAlarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlarm not implemented")
}
func (UnimplementedAlarmRuntimeServer) RunAlarm(context.Context, *RunAlarmRequest) (*RunAlarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAlarm not implemented")
}
func (UnimplementedAlarmRuntimeServer) mustEmbedUnimplementedAlarmRuntimeServer() {}
func (UnimplementedAlarmRuntimeServer) testEmbeddedByValue()                      {}

// UnsafeAlarmRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlarmRuntimeServer will
// result in compilation errors.
type UnsafeAlarmRuntimeServer interface {
	mustEmbedUnimplementedAlarmRuntimeServer()
}

func RegisterAlarmRuntimeServer(s grpc.ServiceRegistrar, srv AlarmRuntimeServer) {
	// If the following call pancis, it indicates UnimplementedAlarmRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlarmRuntime_ServiceDesc, srv)
}

func _AlarmRuntime_ListAlarms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlarmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmRuntimeServer).ListAlarms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmRuntime_ListAlarms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmRuntimeServer).ListAlarms(ctx, req.(*ListAlarmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmRuntime_GetAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmRuntimeServer).GetAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmRuntime_GetAlarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmRuntimeServer).GetAlarm(ctx, req.(*GetAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlarmRuntime_RunAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmRuntimeServer).RunAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlarmRuntime_RunAlarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmRuntimeServer).RunAlarm(ctx, req.(*RunAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlarmRuntime_ServiceDesc is the grpc.ServiceDesc for AlarmRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlarmRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alarmruntime.v1.AlarmRuntime",
	HandlerType: (*AlarmRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAlarms",
			Handler:    _AlarmRuntime_ListAlarms_Handler,
		},
		{
			MethodName: "GetAlarm",
			Handler:    _AlarmRuntime_GetAlarm_Handler,
		},
		{
			MethodName: "RunAlarm",
			Handler:    _AlarmRuntime_RunAlarm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/alarmruntime/v1/runtime.proto",
}
